# This is a basic workflow to help you get started with Actions

name: CD on Tencent

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: centos

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # Build
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true
       
      # Deploy
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
            ARGS: "-avzr --delete"
            SOURCE: "/"
            REMOTE_HOST: "49.232.153.13"
            REMOTE_USER: "root"
            REMOTE_PASSWORD: "Koppel@1025"
            TARGET: "~/app/koa-test"
